#!/usr/bin/env python3
# ============================================================================
# pfasm_tools_w.py (v0.2) — validator + reference machine for PTSG-WPMS-Formation
# (L2 Formation) instruction lists, per Decision Register W v0.7 and
# L2 Formation Register Map v0.3.
#
#  * contract = isa_table_w.json (generated by isa_fold_w.py; never hand-edited)
#  * single block store + bundle presentation (W-F24): no page pair, no CMT
#  * 9-bit ADRS map: store 0x000-07F, inbox view 0x080-0FF, CUR alias 0x100-10F,
#    COMMIT view 0x110-117, sweep words 0x118-119, status 0x11A
#  * write windows (EW4): store written directly only in HK; CUR alias only in a
#    packet window; BCP only in HK
#  * ADD/SUB wrap modulo 2^32 (W-F30); MUL/MAC realign by >> SHV and
#    raise E8 on overflow (saturating) as before
#  * STP (W-F26), BCP (W-F27), WSH (W-F23)
# License: MIT (Layer 3). Illustrative, not normative.
# ============================================================================
import json, math, re, sys

WORD_MIN, WORD_MAX = -(1 << 31), (1 << 31) - 1
NMAX, N_MIN, BLOCKS = 2048, 32, 8

def s32(v):
    v &= 0xFFFFFFFF
    return v - (1 << 32) if v >> 31 else v

def sat(w, errs, ctx):
    if w < WORD_MIN or w > WORD_MAX:
        errs.append(f"E8 arithmetic overflow at {ctx}")
        return max(WORD_MIN, min(WORD_MAX, w))
    return w

# ---------------------------------------------------------------- parse
OPND = r'(#-?(?:0x[0-9A-Fa-f]+|\d+)|@PPM|TEMP|K|I|SN|SSS|ADRS|0x[0-9A-Fa-f]+|\d+)'
def parse(path):
    prog, band = [], None
    for ln, raw in enumerate(open(path), 1):
        line = raw.split(';')[0].strip()
        if not line or line.startswith('.window'): continue
        if line == '.bg': band = 'BG'; continue
        if line == '.q':  band = 'Q';  continue
        m = re.match(r'([A-Z]{3})(?:\s+' + OPND + r')?$', line)
        if not m: raise SyntaxError(f"line {ln}: cannot parse '{line}'")
        prog.append({"ln": ln, "band": band, "mn": m.group(1), "op": m.group(2)})
    return prog

# ---------------------------------------------------------------- validate
SRC_KINDS = {"@PPM": "PPM", "TEMP": "TEMP", "K": "K", "I": "I", "SN": "SN", "SSS": "SSS"}
DST_KINDS = {"TEMP": "TEMP", "@PPM": "STORE", "ADRS": "ADRS"}

def validate(prog, isa):
    errs = []
    srcs, dsts = set(isa["source_ids"].values()), set(isa["dest_ids"].values())
    for p in prog:
        mn, band, op = p["mn"], p["band"], p["op"] or ""
        if band is None:
            errs.append(f"line {p['ln']}: instruction before any band directive"); continue
        spec = isa["instructions"].get(mn)
        if spec is None:
            errs.append(f"line {p['ln']}: {mn} — not in the profile contract (E4)"); continue
        if spec["legality"].get(band) != "Legal":
            errs.append(f"line {p['ln']}: {mn} in {band} band — {spec['legality'].get(band)} ({'E2' if band == 'Q' else 'E1'})")
        if mn in ("LDA", "ADD", "SUB", "MUL", "MAC", "STP"):
            kind = "IMM" if op.startswith("#") else SRC_KINDS.get(op)
            if kind is None or kind not in srcs:
                errs.append(f"line {p['ln']}: {mn} — source '{op}' not in contract (E4)")
        if mn == "STA" and DST_KINDS.get(op) not in dsts:
            errs.append(f"line {p['ln']}: STA — destination '{op}' not in contract (E4; W-F1 if ADRS)")
        if mn in ("SAD", "SFT") and not re.match(r'^-?(0x[0-9A-Fa-f]+|\d+)$', op):
            errs.append(f"line {p['ln']}: {mn} needs a literal")
    return errs

# ---------------------------------------------------------------- machine
BUNDLE_SLOTS = (0x6, 0x7, 0x8, 0x2, 0xF, 0x3, 0x4, 0xE)   # PH0 PHD1 PHD2 LP LS0 LAD1 LAD2 RT.OUT

def sweep_P(w):     return w & 0xF
def sweep_order(w): return [(w >> (4 + 3 * i)) & 7 for i in range(8)]
def make_sweep(order): 
    w = len(order)
    for i, b in enumerate(order): w |= b << (4 + 3 * i)
    return w

class Machine:
    """L2 Formation datapath + block store + inbox + the part of the sweep
    sequencer the datapath can see (CUR alias, phase, take-set)."""
    def __init__(self):
        self.store = [0] * (BLOCKS * 16)
        self.inbox = [[0] * 16 for _ in range(BLOCKS)]
        self.rtout_staged = [0] * BLOCKS
        self.commit = [0] * BLOCKS          # [15:0] slot mask, [16] RT.OUT bit
        self.armed = [False] * BLOCKS
        self.sweep_staged, self.sweep_armed = 0, False
        self.sweep_a = 0                    # CR5-R1: reset = empty sweeps
        self.take, self.copied = set(), set()
        self.take_sweep = self.sweep_copied = self.inbox_taken = False
        self.accm = self.temp = self.adrs = self.shv = 0
        self.phase, self.cur, self.q = 'HK', None, 0
        self.errors = []

    # --- address decode
    def read(self, a, ctx):
        if 0x000 <= a < 0x080: return self.store[a]
        if 0x080 <= a < 0x100:
            b, i = (a - 0x80) >> 4, (a - 0x80) & 15
            return self.rtout_staged[b] if i == 0xE else 0 if i == 0xD else self.inbox[b][i]
        if 0x100 <= a < 0x110:
            return self.store[self.cur * 16 + (a - 0x100)] if self.phase == 'PKT' else 0
        if 0x110 <= a < 0x118:
            b = a - 0x110
            return self.commit[b] | ((b in self.copied) << 29) | ((b in self.take) << 30)
        if a == 0x118: return self.sweep_staged
        if a == 0x119: return self.sweep_a
        if a == 0x11A: return self.q | (sweep_P(self.sweep_a) << 4) | ((self.phase == 'HK') << 8)
        self.errors.append(f"E5 ADRS 0x{a:03X} outside the map at {ctx}"); return 0

    def write(self, a, v, ctx):
        if 0x000 <= a < 0x080:
            if self.phase != 'HK': self.errors.append(f"EW4 direct store write outside HK at {ctx}"); return
            self.store[a] = v; return
        if 0x100 <= a < 0x110:
            if self.phase != 'PKT': self.errors.append(f"EW4 CUR write outside a packet window at {ctx}"); return
            self.store[self.cur * 16 + (a - 0x100)] = v; return
        if 0x080 <= a <= 0x11A: self.errors.append(f"EW3 write to read-only 0x{a:03X} at {ctx}"); return
        self.errors.append(f"E5 ADRS 0x{a:03X} outside the map at {ctx}")

    def src(self, op, ctx, quartet):
        if op.startswith('#'): return int(op[1:], 0)
        if op == '@PPM': return self.read(self.adrs, ctx)
        if op == 'TEMP': return self.temp
        return quartet.get(op, 0)

    # --- W-F27: masked block copy of the GO's take-set
    def bcp(self, ctx):
        if self.phase != 'HK':
            self.errors.append(f"EW4 BCP outside HK at {ctx}"); return 1
        clocks = 1
        for b in sorted(self.take - self.copied):
            m = self.commit[b]
            for i in range(16):
                if i not in (13, 14) and (m >> i) & 1: self.store[b * 16 + i] = self.inbox[b][i]
            if (m >> 16) & 1: self.store[b * 16 + 0xE] = self.rtout_staged[b]
            self.copied.add(b); clocks += 1
        if self.take_sweep and not self.sweep_copied:
            w = self.sweep_staged; P = sweep_P(w); order = sweep_order(w)[:P]
            if P > BLOCKS or len(set(order)) != P:
                self.errors.append(f"EW5 invalid sweep word 0x{w:07X} at {ctx}")
            elif sum(self.store[b * 16] for b in order) > NMAX:
                self.errors.append(f"EW5 sum N > NMAX at {ctx}")
            else:
                self.sweep_a = w
            self.sweep_copied = True; clocks += 1
        w = self.sweep_a; order = sweep_order(w)[:sweep_P(w)]           # backstop for block-only GOs
        if sum(self.store[b * 16] for b in order) > NMAX:
            self.errors.append(f"EW5 sum N of the sweep in effect > NMAX at {ctx}")
        self.inbox_taken = True
        return clocks

    # --- one BG window
    def run(self, prog, phase, cur=None, quartet=None):
        self.phase, self.cur, quartet = phase, cur, (quartet or {})
        clocks = 0
        for p in prog:
            mn, op, ctx = p['mn'], p['op'], f"line {p['ln']}"
            clocks += 1
            if   mn == 'SAD': self.adrs = int(op, 0)
            elif mn == 'LDM': self.accm = self.read(self.adrs, ctx); self.adrs += 1
            elif mn == 'STM': self.write(self.adrs, self.accm, ctx); self.adrs += 1
            elif mn == 'LDA': self.accm = self.src(op, ctx, quartet)
            elif mn == 'STA':
                if op == 'TEMP': self.temp = self.accm
                else: self.write(self.adrs, self.accm, ctx)
            elif mn == 'SWP': self.accm, self.temp = self.temp, self.accm
            elif mn == 'ADD': self.accm = s32(self.accm + self.src(op, ctx, quartet))   # W-F30: wrap
            elif mn == 'SUB': self.accm = s32(self.accm - self.src(op, ctx, quartet))
            elif mn == 'MUL': self.accm = sat((self.accm * self.src(op, ctx, quartet)) >> self.shv, self.errors, ctx)
            elif mn == 'MAC': self.accm = sat(((self.accm * self.temp) >> self.shv) + self.src(op, ctx, quartet), self.errors, ctx)
            elif mn == 'SFT':
                n = int(op, 0); self.accm = sat(self.accm >> n if n >= 0 else self.accm << -n, self.errors, ctx)
            elif mn == 'WSH': self.shv = self.accm & 31
            elif mn == 'STP':
                if self.temp < 0: self.errors.append(f"EW6 STP with negative rate at {ctx}")
                else:
                    d = self.src(op, ctx, quartet) - self.accm          # 33-bit difference
                    self.accm = self.accm + max(-self.temp, min(self.temp, d))
            elif mn == 'BCP': clocks += self.bcp(ctx) - 1
            elif mn in ('WLV', 'WJV'): pass
            else: raise NotImplementedError(mn)
        return clocks

# ---------------------------------------------------------------- main: the exp demo, re-issued (HK-class window)
def main():
    isa = json.load(open(sys.argv[2] if len(sys.argv) > 2 else "isa_table_w.json"))
    prog = parse(sys.argv[1])
    errs = validate(prog, isa)
    print(f"validate: {len(prog)} instructions; " + ("CLEAN" if not errs else f"{len(errs)} VIOLATIONS"))
    for e in errs: print("  " + e)
    if errs: sys.exit(1)
    Q = 28
    to_fix = lambda v: int(round(v * (1 << Q)))
    coef = [to_fix(1 / math.factorial(n)) for n in range(9, -1, -1)]
    worst = (0, None)
    print("sweep x in [-0.5, +0.5], program-owned Q4.28 (SHV=28), 10-term Horner, non-packet window:")
    for i in range(-10, 11):
        x = i * 0.05
        mc = Machine(); mc.store[:11] = [to_fix(x)] + coef
        mc.run(prog, 'HK')
        if mc.errors: print("oracle:", "; ".join(sorted(set(mc.errors)))); sys.exit(2)
        got = mc.store[11] / (1 << Q); err = abs(got - math.exp(x))
        if err > worst[0]: worst = (err, x)
        if i in (-10, 0, 10): print(f"  x={x:+.2f}  exp={math.exp(x):.9f}  got={got:.9f}  |err|={err:.2e}")
    print(f"max |err| over sweep = {worst[0]:.2e} at x={worst[1]:+.2f} (Q4.28 LSB = {2**-Q:.2e})")

if __name__ == "__main__":
    main()
