#!/usr/bin/env python3
# ============================================================================
# gen_l1_tables.py — one source, two consumers (as gen_decode.py for L2): the
# numbers of the L1 pipeline are taken from their owners and written for the
# RTL, so the RTL can never drift from the models.
#   * exp2 table T[256] (Q2.30), C1, C2  <- the customer's oracle (golden),
#     wpms_layer1_oracle._T/_C1/_C2, imported unchanged;
#   * the Maclaurin core's coefficients c0..c5 and stage shifts <- l1_model.py
#     (the published realization).
# Writes hw/l1/wpms_exp2_table.hex ($readmemh), hw/l1/wpms_exp2_table.mif (M10K)
# and hw/l1/wpms_l1_consts.vh.
#
#   python3 gen_l1_tables.py [--check]     # --check: compare, do not write
# License: MIT (Layer 3).
# ----------------------------------------------------------------------------
# REVISION HISTORY(RH)
# 001 2026-09-29       Claude Code   Add : First version (SILICON_BRIEF Phase 4).
# ============================================================================
import os, sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import l1_model as M                     # noqa: E402
O = M.O
L1 = os.path.normpath(os.path.join(HERE, "..", "l1"))


def texts():
    T = O._T
    assert len(T) == 256 and all(0 < t < (1 << 31) for t in T)
    hexs = "".join(f"{t:08X}\n" for t in T)
    mif = ["-- wpms_exp2_table.mif — generated by hw/tools/gen_l1_tables.py from the customer's oracle",
           "-- (wpms_layer1_oracle._T: round(2^(i/256) * 2^30), Q2.30). Do not edit.",
           "WIDTH=31;", "DEPTH=256;", "ADDRESS_RADIX=UNS;", "DATA_RADIX=UNS;", "CONTENT BEGIN"]
    mif += [f"    {i} : {t};" for i, t in enumerate(T)] + ["END;", ""]
    c = M.SIN_C
    vh = f"""// ============================================================================
//  wpms_l1_consts.vh — GENERATED by hw/tools/gen_l1_tables.py. Do not edit.
//  exp2 (Ch.3 §3.5.4): C1, C2 and the table (wpms_exp2_table.hex/.mif) are the
//  customer's oracle's own integers (wpms_layer1_oracle._C1/_C2/_T).
//  Maclaurin core (Ch.2 v1.1): the published realization of hw/tools/l1_model.py
//  — Horner in U = u^2 (u = in-quadrant phase in cycles), c_j = (2 pi)^(2j+1)/(2j+1)!
//  at per-stage power-of-two scales; S1 at 2^{M.SIN_E[1]}, S2 2^{M.SIN_E[2]}, S3 2^{M.SIN_E[3]}, S4 2^{M.SIN_E[4]}, S5 2^{M.SIN_E[5]}, c5 2^{M.SIN_F5}.
//  License: MIT (Layer 3).
// ============================================================================
localparam [29:0] EXP2_C1 = 30'd{O._C1};      // round(ln2 * 2^30)
localparam [27:0] EXP2_C2 = 28'd{O._C2};      // round(ln2^2/2 * 2^30)
localparam [25:0] SIN_C0  = 26'd{c[0]};       // 2 pi            * 2^{M.SIN_E[1]}
localparam [25:0] SIN_C1  = 26'd{c[1]};       // (2 pi)^3/3!     * 2^{M.SIN_E[2]}
localparam [25:0] SIN_C2  = 26'd{c[2]};       // (2 pi)^5/5!     * 2^{M.SIN_E[3]}
localparam [25:0] SIN_C3  = 26'd{c[3]};       // (2 pi)^7/7!     * 2^{M.SIN_E[4]}
localparam [25:0] SIN_C4  = 26'd{c[4]};       // (2 pi)^9/9!     * 2^{M.SIN_E[5]}
localparam [25:0] SIN_C5  = 26'd{c[5]};       // (2 pi)^11/11!   * 2^{M.SIN_F5}
localparam integer SIN_SH5 = {M.SIN_SH[5]};   // U*c5 -> S5
localparam integer SIN_SH4 = {M.SIN_SH[4]};   // U*S5 -> S4
localparam integer SIN_SH3 = {M.SIN_SH[3]};   // U*S4 -> S3
localparam integer SIN_SH2 = {M.SIN_SH[2]};   // U*S3 -> S2
localparam integer SIN_SH1 = {M.SIN_SH[1]};   // U*S2 -> S1
localparam integer SIN_SH0 = {M.SIN_SH[0]};   // u*S1 -> Q0.40
"""
    return {"wpms_exp2_table.hex": hexs, "wpms_exp2_table.mif": "\n".join(mif), "wpms_l1_consts.vh": vh}


def main():
    check = "--check" in sys.argv
    bad = 0
    for name, text in texts().items():
        path = os.path.join(L1, name)
        if check:
            same = os.path.exists(path) and open(path).read() == text
            bad += not same
            print(f"  {name}: {'equal' if same else 'DIFFERS'}")
        else:
            open(path, "w").write(text)
            print(f"  wrote {os.path.relpath(path, os.path.join(HERE, '..'))}")
    print(f"gen_l1_tables: {'CHECK ' + ('PASS' if not bad else 'FAIL') if check else 'done'}")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
