#!/usr/bin/env python3
# ============================================================================
# gen_switch_rom.py — the built-in ROM of the input switch (customer Ch.5 §5.8):
# the test origin as a list of (address, data) writes ending in GO_ALL, one
# image per NMAX (ruling 2026-09-30, SD-17 (a): N = 1,008 on the 50 MHz build;
# the 100 MHz build keeps the text's 2,048).
#   * the block: Ch.3 §3.10 (Fixed) — f0 = 996 Hz, df = 1/256 Hz, A = 0.97,
#     phases 0 — computed here with the customer's oracle's own formula and
#     constants (wpms_layer1_oracle FS, M32; imported unchanged) and checked
#     against the integers the text prints; LPT = LP, LE0 = 0 (Ch.5 §5.8);
#   * the list: Ch.5 §5.8 — module 0 block 0 with the full mask, SWEEP =
#     {P = 1, order 0}, MG_TARGET = 0, all owners = port 0, then GO_ALL.
# Writes hw/switch/wpms_rom_origin_<N>.hex ($readmemh) and .mif (M10K, ISMCE).
# Word: {address[11:0], data[31:0]}; address 0xFFF ends the list.
#
#   python3 gen_switch_rom.py [--check]     # --check: compare, do not write
# License: MIT (Layer 3).
# ----------------------------------------------------------------------------
# REVISION HISTORY(RH)
# 001 2026-09-30       Claude Code   Add : First version (SILICON_BRIEF Phase 5).
# ============================================================================
import math, os, sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import l1_model as M                     # noqa: E402  (imports the customer's oracle unchanged)
O = M.O
SW = os.path.normpath(os.path.join(HERE, "..", "switch"))
DEPTH = 256
END = 0xFFF
FULL_MASK = 0x9FFF | 1 << 16             # every writable slot (13, 14 ignored) + RT.OUT
ARM, GO_ALL = 1 << 30, 0x2


def origin_block(N):
    """Ch.3 §3.10 with Ch.5 §5.8's LPT = LP, LE0 = 0: the 16 slots of the page block."""
    f0, df, A = 996.0, 1 / 256, 0.97                     # Ch.3 §3.10 / Ch.1 §1.11
    om0 = round(f0 * O.M32 / O.FS) % O.M32               # the oracle's CH3-ORIGIN formula
    omd1 = round(df * O.M32 / O.FS)
    lp = round(math.log2(A) * 2 ** 26)
    assert (om0, omd1, lp) == (89_120_571, 350, -2_948_988), (om0, omd1, lp)   # the integers Ch.3 prints
    v = [0] * 16
    v[0x0] = N
    v[0x2] = v[0x9] = lp                                  # LP, LPT
    v[0xA] = om0
    v[0xB] = omd1
    return v


def rom_list(N):
    """[(address, data, comment)] in play order."""
    v = origin_block(N)
    names = ["N", "TAG", "LP", "LAD1", "LAD2", "LE0", "PH0", "PHD1", "PHD2", "LPT", "OM0", "OMD1", "OMD2",
             None, None, "LS0"]
    L = [(0x200 + i, v[i] & 0xFFFFFFFF, f"INBOX[0][0x{i:X}] {names[i]} = {v[i]}")
         for i in range(16) if names[i] is not None]
    L += [(0x280, 3, "RTOUT[0] = 0b11 (L and R)"),
          (0x288, FULL_MASK | ARM, "COMMIT[0] = full mask + RT.OUT, arm"),
          (0x290, 1 | 0 << 4, "SWEEP = {P = 1, order 0}"),
          (0x291, ARM, "SWEEP_COMMIT: arm"),
          (0x010, 0, "MG_TARGET = 0"),
          (0x020, 0, "OWNER[0] = all port 0"),
          (0x008, GO_ALL, "GO: GO_ALL")]
    return L


def texts(N):
    L = rom_list(N)
    assert len(L) < DEPTH
    words = [(a << 32) | d for a, d, _ in L] + [END << 32]
    hexs = [f"// wpms_rom_origin_{N}.hex — generated by hw/tools/gen_switch_rom.py (Ch.3 §3.10, Ch.5 §5.8). Do not edit.",
            "// {address[11:0], data[31:0]}; address FFF ends the list."]
    hexs += [f"{w:011X}   // {c}" for w, (_, _, c) in zip(words, L)] + [f"{END << 32:011X}   // end"]
    hexs += [f"{END << 32:011X}" for _ in range(DEPTH - len(words))] + [""]      # the whole depth (no short read)
    mif = [f"-- wpms_rom_origin_{N}.mif — generated by hw/tools/gen_switch_rom.py (Ch.3 §3.10, Ch.5 §5.8). Do not edit.",
           "-- The input switch's built-in ROM (port 3): {address[11:0], data[31:0]}; address FFF ends the list.",
           "-- ISMCE may overwrite it (instance TORG); a reconfiguration restores this image.",
           "WIDTH=44;", f"DEPTH={DEPTH};", "ADDRESS_RADIX=UNS;", "DATA_RADIX=HEX;", "CONTENT BEGIN"]
    mif += [f"    {i} : {w:011X};" for i, w in enumerate(words)]
    mif += [f"    [{len(words)}..{DEPTH - 1}] : {END << 32:011X};", "END;", ""]
    return "\n".join(hexs), "\n".join(mif)


def main():
    check = "--check" in sys.argv
    bad = 0
    for N in (1008, 2048):
        h, m = texts(N)
        for name, t in ((f"wpms_rom_origin_{N}.hex", h), (f"wpms_rom_origin_{N}.mif", m)):
            path = os.path.join(SW, name)
            if check:
                same = os.path.exists(path) and open(path).read() == t
                print(f"  {name}: {'identical' if same else 'DIFFERENT'}")
                bad += not same
            else:
                open(path, "w").write(t)
                print(f"  wrote {os.path.relpath(path, os.path.join(HERE, '..'))}")
    if check:
        print(f"gen_switch_rom --check: {'PASS' if not bad else 'FAIL'}")
        sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
