#!/usr/bin/env python3
# ============================================================================
# gen_decode.py — one source, two consumers: from hw/tools/decode_map.json
# generate the RTL decoder table (hw/l2/wpms_decode.vh) and the published map
# (hw/l2/decode_map.md) after checking the map against the profile contract
# (03_Sample_Implementations/tools/isa_table_w.json). The assemblers
# (pfasm_as.py, score_as.py) read the same JSON.
#
#   python3 gen_decode.py [--check]      (--check: verify only, write nothing)
#
# Checks: every contract instruction is in the map with the same {mode, sub-op};
# the map has no instruction the contract lacks; every row the contract removed
# (RTW, CMT, PSH, POP, WSV) is absent from the decodable set and listed as E4;
# source/destination IDs equal the contract's; field layout tiles D0-D31.
# License: MIT (Layer 3).
# ----------------------------------------------------------------------------
# REVISION HISTORY(RH)
# 001 2026-09-27       Claude Code   Add : First version (SILICON_BRIEF Phase 2).
# 002 2026-09-27       Claude Code   Add : decode_map.md generated from the same JSON.
# ============================================================================
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MAP = os.path.join(HERE, "decode_map.json")
CONTRACT = os.path.normpath(os.path.join(HERE, "..", "..", "tools", "isa_table_w.json"))
OUT = os.path.normpath(os.path.join(HERE, "..", "l2", "wpms_decode.vh"))
OUT_MD = os.path.normpath(os.path.join(HERE, "..", "l2", "decode_map.md"))


def load():
    return json.load(open(MAP)), json.load(open(CONTRACT))


def check(dm, isa):
    errs = []
    ins, rem = dm["instructions"], dm["removed_rows_E4"]
    for mn, spec in isa["instructions"].items():
        if mn not in ins:
            errs.append(f"contract instruction {mn} missing from the map")
        elif (ins[mn]["mode"], ins[mn]["subop"]) != (spec["mode"], spec["subop"]):
            errs.append(f"{mn}: map {ins[mn]['mode']}.{ins[mn]['subop']} != contract {spec['mode']}.{spec['subop']}")
    for mn in ins:
        if mn not in isa["instructions"]:
            errs.append(f"map instruction {mn} is not in the contract")
    seen = {}
    for mn, s in ins.items():
        key = (s["mode"], s["subop"])
        if key in seen: errs.append(f"{mn} and {seen[key]} share {key}")
        seen[key] = mn
        if not (1 <= s["mode"] <= 15 and 0 <= s["subop"] <= 15): errs.append(f"{mn}: mode/sub-op out of field range")
    for mn, s in rem.items():
        if mn in isa["instructions"]: errs.append(f"removed row {mn} is still in the contract")
        if (s["mode"], s["subop"]) in seen: errs.append(f"removed row {mn} collides with {seen[(s['mode'], s['subop'])]}")
    src = {v: int(k) for k, v in isa["source_ids"].items()}
    dst = {("STORE" if v in ("STORE", "PPM_SHADOW") else v): int(k) for k, v in isa["dest_ids"].items()}
    if src != dm["source_ids"]: errs.append(f"source IDs differ: map {dm['source_ids']} contract {src}")
    if dst != dm["dest_ids"]: errs.append(f"destination IDs differ: map {dm['dest_ids']} contract {dst}")
    bits = []
    for f in dm["word"].values():
        bits += list(range(f["lsb"], f["lsb"] + f["width"]))
    if sorted(bits) != list(range(32)): errs.append("word fields do not tile D0-D31 exactly once")
    return errs


def emit(dm):
    w, k = dm["word"], dm["operand_kinds"]
    L = []
    a = L.append
    a("// ============================================================================")
    a("//  wpms_decode.vh — GENERATED by hw/tools/gen_decode.py from hw/tools/decode_map.json")
    a("//  DO NOT EDIT. Change the JSON and regenerate; pfasm_as.py reads the same JSON.")
    a("//  Checked against 03_Sample_Implementations/tools/isa_table_w.json.")
    a("//  License: MIT (Layer 3).")
    a("// ============================================================================")
    a(f"// Word layout: opcode D{w['opcode']['lsb']}-D{w['opcode']['lsb']+3} (Global = 0), "
      f"mode D{w['mode']['lsb']}-D{w['mode']['lsb']+3}, sub-op D{w['subop']['lsb']}-D{w['subop']['lsb']+3}, "
      f"register ID D{w['rid']['lsb']}-D{w['rid']['lsb']+3}, immediate D{w['imm']['lsb']}-D{w['imm']['lsb']+15}.")
    a("// On the Core's external-operation bus: mode = ext_op_subopcode, {rid, subop} = ext_op_sub_operand,")
    a("// imm = ext_op_data.")
    a("")
    a("// ---- operand kinds (how rid and imm are read) ----")
    for name, spec in k.items():
        a(f"localparam [2:0] K_{name.upper():5s} = 3'd{spec['code']};   // rid: {spec['rid']}; imm: {spec['imm']}")
    a("")
    a("// ---- internal operation codes ----")
    for mn, s in sorted(dm["instructions"].items(), key=lambda kv: kv[1]["op"]):
        a(f"localparam [3:0] OP_{mn} = 4'd{s['op']};   // {s['mode']}.{s['subop']}")
    a("")
    a("// ---- source and destination IDs (master Ch.2 section 2.9; contract) ----")
    for n, v in dm["source_ids"].items():
        a(f"localparam [3:0] SRC_{n:5s} = 4'd{v};")
    for n, v in dm["dest_ids"].items():
        a(f"localparam [3:0] DST_{n:5s} = 4'd{v};")
    a("")
    a("// ---- error codes (error_code[4:0]: bit 4 = profile row EWn) ----")
    for n, v in dm["error_codes"].items():
        a(f"localparam [4:0] ERR_{n:3s} = 5'd{v['code']};   // {v['cause']}")
    a("")
    a("// ---- decoder table: {legal, kind[2:0], op[3:0]} from {mode, sub-op} ----")
    a("// Anything not listed (removed rows " + ", ".join(f"{m} {s['mode']}.{s['subop']}" for m, s in dm['removed_rows_E4'].items())
      + "; unassigned sub-ops; modes 5-15) decodes illegal -> E4.")
    a("function [7:0] wpms_decode;")
    a("    input [3:0] mode;")
    a("    input [3:0] subop;")
    a("    begin")
    a("        case ({mode, subop})")
    for mn, s in sorted(dm["instructions"].items(), key=lambda kv: (kv[1]["mode"], kv[1]["subop"])):
        a(f"        8'h{s['mode']:X}{s['subop']:X}: wpms_decode = {{1'b1, K_{s['kind'].upper():5s}, OP_{mn}}};")
    a("        default: wpms_decode = 8'h00;")
    a("        endcase")
    a("    end")
    a("endfunction")
    a("")
    return "\n".join(L) + "\n"


def enc(dm, mode, subop, rid=0, imm=0):
    w = dm["word"]
    return ((imm & 0xFFFF) << w["imm"]["lsb"]) | ((rid & 0xF) << w["rid"]["lsb"]) | \
           ((subop & 0xF) << w["subop"]["lsb"]) | ((mode & 0xF) << w["mode"]["lsb"])


def emit_md(dm):
    w, k, ins = dm["word"], dm["operand_kinds"], dm["instructions"]
    S, D = dm["source_ids"], dm["dest_ids"]
    L = []
    a = L.append
    a("# PTSG-WPMS-Formation — Instruction Decode Map / 命令デコード表")
    a("")
    a(f"*v{dm['provenance']['version']} · {dm['provenance']['date']} · {dm['provenance']['license']} · "
      "GENERATED by `hw/tools/gen_decode.py` from `hw/tools/decode_map.json` — do not edit; change the JSON and regenerate.*")
    a("")
    a("*生成物。`decode_map.json` が唯一の源で、RTL のデコード表 (`wpms_decode.vh`)、アセンブラ (`pfasm_as.py`, `score_as.py`)、"
      "本書の三つがそこから作られる。手で編集しないこと。*")
    a("")
    a("This is the Implementation-Arena part of the profile's encoding (master Ch.3 CL-5): *which* {mode, sub-op} exist and "
      "the source/destination ID numbers are fixed by the contract (`isa_table_w.json`, master Ch.2 §2.9); "
      "*where* the sub-op, the register ID and the immediate sit inside D8–D31 is fixed here. "
      "`gen_decode.py` checks the map against the contract before it writes anything.")
    a("")
    a("契約（`isa_table_w.json`）が決めるのは {mode, sub-op} の有無と ID 番号。本表が決めるのは D8–D31 内のビット位置（実装アリーナ）。")
    a("")
    a("## 1. Word layout / 語の配置")
    a("")
    a("| Field | Bits | On the Core's bus | Note |")
    a("|---|---|---|---|")
    bus = {"opcode": "— (the Core consumes it)", "mode": "`ext_op_subopcode[3:0]`", "subop": "`ext_op_sub_operand[3:0]`",
           "rid": "`ext_op_sub_operand[7:4]`", "imm": "`ext_op_data[15:0]`"}
    for name, f in w.items():
        note = re.sub(r";\s*on the bus as \S+\s*", " ", f["note"].split(": ", 1)[-1]).strip()
        a(f"| {name} | D{f['lsb']}–D{f['lsb'] + f['width'] - 1} | {bus[name]} | {note} |")
    a("")
    a("```")
    a(" 31                    16 15    12 11     8 7      4 3      0")
    a("+-----------------------+--------+--------+--------+--------+")
    a("|   imm / literal (16)  |  rid   | sub-op |  mode  |  0000  |   Core Global, mode 1..15")
    a("+-----------------------+--------+--------+--------+--------+")
    a("```")
    a("")
    a("語は Core の Global（opcode 0）で mode ≥ 1。バス上では mode = `ext_op_subopcode`、{rid, sub-op} = `ext_op_sub_operand`、"
      "即値 = `ext_op_data`。")
    a("")
    a("## 2. Operand kinds / オペランドの種類")
    a("")
    a("| Kind | rid (D12–D15) | imm (D16–D31) |")
    a("|---|---|---|")
    for name, spec in k.items():
        a(f"| {name} | {spec['rid']} | {spec['imm']} |")
    a("")
    a(f"**Must be zero.** {dm['must_be_zero_rule']}")
    a("")
    a("**ゼロ必須。** 命令が使わないフィールドは 0。0 以外は E4（沈黙は意味ではない）。アセンブラはそのような語を出さない。")
    a("")
    a("## 3. Instructions / 命令")
    a("")
    a("| Mnemonic | mode·sub-op | Kind | Word (fields) | Example | Word |")
    a("|---|---|---|---|---|---|")
    ex = {"LDA": ("LDA #28", S["IMM"], 28), "STA": ("STA @PPM", D["STORE"], 0), "ADD": ("ADD @PPM", S["PPM"], 0),
          "SUB": ("SUB TEMP", S["TEMP"], 0), "MUL": ("MUL K", S["K"], 0), "MAC": ("MAC @PPM", S["PPM"], 0),
          "SWP": ("SWP", 0, 0), "SFT": ("SFT -4", 0, -4), "SAD": ("SAD 0x105", 0, 0x105), "LDM": ("LDM", 0, 0),
          "STM": ("STM", 0, 0), "WLV": ("WLV", 0, 0), "WJV": ("WJV", 0, 0), "WSH": ("WSH", 0, 0),
          "STP": ("STP @PPM", S["PPM"], 0), "BCP": ("BCP", 0, 0)}
    tmpl = {"none": "0000 · 0 · s · m · 0", "src": "imm · srcID · s · m · 0", "dst": "0000 · dstID · s · m · 0",
            "lit9": "0000000·lit9 · 0 · s · m · 0", "shift": "count · 0 · s · m · 0"}
    for mn, spec in sorted(ins.items(), key=lambda kv: (kv[1]["mode"], kv[1]["subop"])):
        e, rid, imm = ex[mn]
        word = enc(dm, spec["mode"], spec["subop"], rid, imm)
        a(f"| {mn} | {spec['mode']}·{spec['subop']} | {spec['kind']} | {tmpl[spec['kind']]} | `{e}` | `{word:08X}` |")
    a("")
    a("LDM and STM always post-increment ADRS (Map v0.3 §3). / LDM・STM は常に ADRS を後置加算する。")
    a("")
    a("## 4. Rows the profile removed — E4 / 削除行（E4）")
    a("")
    a("| Row | mode·sub-op | Why | Word on the bus decodes to |")
    a("|---|---|---|---|")
    for mn, spec in dm["removed_rows_E4"].items():
        a(f"| {mn} | {spec['mode']}·{spec['subop']} | {spec['why']} | E4 |")
    a("")
    a("Every {mode, sub-op} not in §3 decodes to E4 as well: unassigned sub-ops of modes 1–4, and modes 5–15. "
      "The hardware checks this (`wpms_decode.vh`); the validator (`pfasm_tools_w.py`) checks the removed mnemonics.")
    a("")
    a("§3 にない {mode, sub-op} はすべて E4（モード 1–4 の未割当サブオペ、モード 5–15）。")
    a("")
    a("## 5. Source and destination IDs / ソース・デスティネーション ID")
    a("")
    a("| Source | ID | | Destination | ID |")
    a("|---|---|---|---|---|")
    srcs, dsts = list(S.items()), list(D.items())
    for i in range(max(len(srcs), len(dsts))):
        s1 = srcs[i] if i < len(srcs) else ("", "")
        d1 = dsts[i] if i < len(dsts) else ("", "")
        a(f"| {s1[0]} | {s1[1]} | | {d1[0]} | {d1[1]} |")
    a("")
    a(f"Reserved → E4. Sources: {dm['source_ids_reserved_E4']}. Destinations: {dm['dest_ids_reserved_E4']}.")
    a("")
    a("予約 ID は E4。ID の番号は契約（マスター第2章 §2.9）が規範、ビット位置のみ本表。")
    a("")
    a("## 6. Error codes (`error_code[4:0]`) / エラーコード")
    a("")
    a("| Row | Code | Cause |")
    a("|---|---|---|")
    for n, v in dm["error_codes"].items():
        a(f"| {n} | {v['code']} (0x{v['code']:02X}) | {v['cause']} |")
    a("")
    a("Bit 4 marks the profile's own rows (EW*). E1/E2 are validator-only: the Core's bus carries no band (SD-01, SD-02). "
      "/ ビット4はプロファイル固有行（EW*）。E1/E2 は検証器のみ（バスに帯域がない：SD-01, SD-02）。")
    a("")
    a("## 7. Timing-signal bits of the score / 楽譜のタイミング信号ビット")
    a("")
    a("| Name | Bits | Meaning |")
    a("|---|---|---|")
    for n, v in dm["timing_signal_bits"].items():
        if n == "free":
            a(f"| (free) | {v} | — |")
        else:
            bits = f"timing_signals[{v['bit']}]" if "bit" in v else f"timing_signals[{v['lsb'] + v['width'] - 1}:{v['lsb']}]"
            a(f"| {n} | {bits} | {v['note'].split(': ', 1)[-1]} |")
    a("")
    a("`score_as.py` writes them (`PKT`, `CSEL=STROBE|NONEMPTY|MORE`) into D16–D31 of Stay Set and Stay words "
      "(Deliverable 2; Deliverable 3 §4). / `score_as.py` が Stay Set と Stay の D16–D31 に書く。")
    a("")
    a("## 8. Assembler operands / アセンブラのオペランド")
    a("")
    a("| Operand | Meaning |")
    a("|---|---|")
    for n, v in dm["assembler_operands"].items():
        a(f"| `{n}` | {v} |")
    a("")
    return "\n".join(L)


def main():
    dm, isa = load()
    errs = check(dm, isa)
    if errs:
        for e in errs: print("gen_decode: ERROR:", e)
        sys.exit(1)
    text, md = emit(dm), emit_md(dm)
    if "--check" in sys.argv:
        old = open(OUT).read() if os.path.exists(OUT) else ""
        old_md = open(OUT_MD).read() if os.path.exists(OUT_MD) else ""
        print("gen_decode: map consistent with the contract;", "RTL table up to date" if old == text else "RTL table STALE",
              "; published map up to date" if old_md == md else "; published map STALE")
        sys.exit(0 if (old == text and old_md == md) else 1)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    open(OUT_MD, "w").write(md)
    print(f"gen_decode: {len(dm['instructions'])} instructions, {len(dm['removed_rows_E4'])} removed rows -> E4; "
          f"wrote {os.path.relpath(OUT)} and {os.path.relpath(OUT_MD)}")


if __name__ == "__main__":
    main()
