#!/usr/bin/env python3
# ============================================================================
# gen_inject_scores.py — the error-injection images of Phase 6 (evidence item
# 6: "each EW2-EW6 injected: error_flag with the right code; L1 silent").
#
# On the board the input switch stands in front of the Formation and refuses
# what would raise EW2 and EW5 from the inbox (PR-1, PR-2), so those rows, and
# the window rows EW3 and EW4, are injected the way the Core's harness swaps
# programs: an image of the R1 dispatch score (wpms_r1d.score) whose packet
# window is replaced, loaded into the instruction memory over JTAG with the
# In-System Memory Content Editor (instance PTSG), then a reset. EW6 needs no
# image: the host writes LE0 = -1 (hw/tools/host/wpms_phase6_steps.py ew6).
#
#   EW2  the window writes N = 16 into its block (CUR slot 0): the
#        post-housekeeping prefetch of that block finds N outside [32, NMAX]
#   EW3  the window stores into the inbox view (negative_tests N4)
#   EW4  the window writes the store directly (negative_tests N1)
#   EW5  the window writes N = NMAX + 1 into its block (in range for a slot):
#        housekeeping's BCP re-checks the sum of N of the sweep in effect
# Each image is the whole score (1,024 words); only the packet window differs. The
# score and its window are kept beside the images (hw/tools/phase6_evidence.py --score
# reads the labels from them: the shorter window moves POS1..POS7).
#
#   python3 gen_inject_scores.py [--check]      writes / compares hw/de10_nano/inject/
# License: MIT (Layer 3 tooling).
# ----------------------------------------------------------------------------
# REVISION HISTORY(RH)
# 001 2026-10-01       Claude Code   Add : First version (SILICON_BRIEF Phase 6).
# ============================================================================
import argparse, os, shutil, sys, tempfile

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import score_as as SA                   # noqa: E402

HW = os.path.normpath(os.path.join(HERE, ".."))
SCORE = os.path.join(HW, "l2", "scores", "wpms_r1d.score")
HKD = os.path.join(HW, "l2", "programs", "wpms_housekeeping_dispatch.pfasm")
OUT = os.path.join(HW, "de10_nano", "inject")


def windows(nmax):
    return {
        "ew2": ("the window writes N = 16 into its own block (CUR slot 0); the next prefetch: EW2",
                ".bg\n        SAD     0x100\n        LDA     #16\n        STM\n"),
        "ew3": ("the window stores into the inbox view (negative_tests N4): EW3",
                ".bg\n        SAD     0x082\n        STM\n"),
        "ew4": ("the window writes the store directly (negative_tests N1): EW4",
                ".bg\n        SAD     0x006\n        LDM\n        SAD     0x00A\n        ADD     @PPM\n"
                "        SAD     0x006\n        STM\n"),
        f"ew5_{nmax}": (f"the window writes N = {nmax + 1} into its block; housekeeping's BCP re-checks "
                        f"the sum of N of the sweep in effect: EW5",
                        f".bg\n        SAD     0x100\n        LDA     #{nmax + 1}\n        STM\n"),
    }


def sources(name, what, prog):
    """The injection score and its window, as they are kept in hw/de10_nano/inject/."""
    win = (f"; inject_{name}.pfasm — Phase 6 error injection, generated by hw/tools/gen_inject_scores.py\n"
           f"; {what}\n; License: MIT (Layer 3 tooling).\n.window inject_{name}\n" + prog)
    src = open(SCORE).read()
    assert src.count(".window PKT wpms_packet.pfasm") == 1
    assert src.count(".window HKD ../programs/wpms_housekeeping_dispatch.pfasm") == 1
    src = src.replace(".window PKT wpms_packet.pfasm", f".window PKT inject_{name}.pfasm")
    src = src.replace(".window HKD ../programs/wpms_housekeeping_dispatch.pfasm",
                      ".window HKD ../../l2/programs/wpms_housekeeping_dispatch.pfasm")
    head = (f"; wpms_r1d_{name}.score — generated by hw/tools/gen_inject_scores.py from\n"
            f"; hw/l2/scores/wpms_r1d.score: the packet window replaced (Phase 6 error injection:\n"
            f"; {what}). Everything below is the R1 dispatch score unchanged.\n")
    return head + src, win


def images():
    out = {}
    for nmax in (1008, 2048):
        for name, (what, prog) in windows(nmax).items():
            if name in out:
                continue
            score, win = sources(name, what, prog)
            with tempfile.TemporaryDirectory() as t:
                os.makedirs(os.path.join(t, "de10_nano", "inject"))
                os.makedirs(os.path.join(t, "l2", "programs"))
                shutil.copy(HKD, os.path.join(t, "l2", "programs"))
                sp = os.path.join(t, "de10_nano", "inject", f"wpms_r1d_{name}.score")
                open(sp, "w").write(score)
                open(os.path.join(t, "de10_nano", "inject", f"inject_{name}.pfasm"), "w").write(win)
                words, info = SA.assemble(sp)
            title = f"wpms_r1d_{name}.score (Phase 6 injection: {what})"
            out[name] = dict(score=score, pfasm=win, hex=SA.to_hex(words, info, title),
                             mif=SA.to_mif(words, info, title), what=what)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    bad = 0
    for name, im in images().items():
        for fn, text in ((f"wpms_r1d_{name}.score", im["score"]), (f"inject_{name}.pfasm", im["pfasm"]),
                         (f"wpms_r1d_{name}.hex", im["hex"]), (f"wpms_r1d_{name}.mif", im["mif"])):
            p = os.path.join(OUT, fn)
            if a.check:
                same = os.path.exists(p) and open(p).read() == text
                bad += not same
                print(f"  {'same' if same else 'DIFFERENT'}  {os.path.basename(p)}")
            else:
                open(p, "w").write(text)
                print(f"  wrote {os.path.basename(p)}  ({im['what']})")
    if a.check:
        print(f"gen_inject_scores: {'PASS' if not bad else 'FAIL'} ({bad} different)")
        sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
