#!/usr/bin/env python3
# ============================================================================
# wpms_phase6_steps.py — OUTSIDE WPMS: the host's part of the Phase 6 evidence
# captures, written once and played two ways (as wpms_music.py): Tcl for
# quartus_stp on the board (wpms_issp_host.tcl), and commands for the
# board-level bench (hw/de10_nano/sim/DE10_Nano_wpms_tb.v, driven by
# hw/tools/cosim_board.py). Integers only cross (C3-D1).
#
#   first_go  after the test origin, one GO: a C-major triad on blocks 1-3
#             (sweep [1, 2, 3]); no knob is written, so every sample stays
#             comparable with the model (evidence item 8)
#   full8     one GO arming all eight blocks with the full mask and RT.OUT and
#             the sweep word [0 .. 7]: the full take-set (BCP, item 4) and a
#             full-load sweep, sum of N = NMAX (items 1 and 5)
#   ew6       LE0 = -1 lands in block 0 while it plays: its next packet
#             window's STP raises EW6 (item 6; the switch has no check on LE0)
#
#   python3 wpms_phase6_steps.py [--nmax 1008|2048] [--out DIR]   (writes the .tcl files; both NMAX by default)
# Every GO is followed by a wait for it to be applied; the Tcl prints
# "applied GO g at sweep s" and the bench reads GO_SEQ / APPLIED_SEQ /
# APPLIED_SAMPLE, so hw/tools/phase6_evidence.py knows where each GO landed.
# License: MIT (Layer 3 tooling; not part of the WPMS design).
# ----------------------------------------------------------------------------
# REVISION HISTORY(RH)
# 001 2026-10-01       Claude Code   Add : First version (SILICON_BRIEF Phase 6).
# ============================================================================
import argparse, os, sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import wpms_music as MU                  # noqa: E402

ARM, GONOW = 1 << 30, 1 << 31
FULL = 0xFFFF & ~(1 << 13 | 1 << 14) | MU.RT_BIT     # every slot (13, 14 are not slots) and RT.OUT


def first_go(nmax=1008):
    C5, E5, G5 = 523.2511, 659.2551, 783.9909
    N = 240 if nmax >= 1008 else 120
    S = [("Q", 0x009, "GO_SEQ (the ROM's GO)"), ("Q", 0x00B, "APPLIED_SAMPLE (the ROM's GO)")]
    for b, f in ((1, C5), (2, E5), (3, G5)):
        S += MU.stage(b, MU.note_block(f, N), rt=(1, 3, 2)[b - 1], note=f"triad {b}")
    S += [("W", 0x290, MU.sweep_word([1, 2, 3]), "SWEEP [1, 2, 3]"), ("W", 0x291, ARM, "SWEEP_COMMIT arm"),
          ("W", 0x008, 1, "GO"), ("APPLY", "C major"), ("SOUND", 1000, "C major")]
    return S


def full8(nmax=1008):
    N = nmax // 8                                     # 126 at 1,008; 256 at 2,048: sum = NMAX
    S = [("Q", 0x009, "GO_SEQ"), ("Q", 0x00B, "APPLIED_SAMPLE")]
    base = 261.6256                                   # C4, then a whole-tone ladder
    for b in range(8):
        v = MU.note_block(base * 2 ** (2 * b / 12), N)
        S += MU.stage(b, v, rt=(1, 2, 3)[b % 3], mask=FULL, note=f"full8 {b}")
    S += [("W", 0x290, MU.sweep_word(list(range(8))), "SWEEP [0 .. 7], P = 8"),
          ("W", 0x291, ARM, "SWEEP_COMMIT arm"), ("W", 0x008, 1, "GO: eight blocks and the sweep word"),
          ("APPLY", "full take-set, full load"), ("SOUND", 1000, "eight notes, sum of N = NMAX"),
          ("Q", 0x299, "SWEEP_CLOCKS_MAX"), ("Q", 0x018, "STROBE_INTERVAL")]
    return S


def ew6(nmax=1008):
    return [("Q", 0x009, "GO_SEQ"),
            ("W", 0x205, 0xFFFFFFFF, "INBOX[0][5] LE0 = -1"),
            ("W", 0x288, (1 << 5) | ARM, "COMMIT[0] LE0, arm"),
            ("W", 0x008, 1, "GO"), ("APPLY", "LE0 < 0 in block 0"), ("SOUND", 200, "EW6 expected")]


CASES = dict(first_go=first_go, full8=full8, ew6=ew6)


def to_stim(steps, after=None):
    """Commands for DE10_Nano_wpms_tb.v: APPLY waits 3 strobes and reads GO_SEQ, APPLIED_SEQ, APPLIED_SAMPLE."""
    L = []
    for st in steps:
        if st[0] == "W": L.append(f"W {st[1]:x} {st[2] & 0xFFFFFFFF:x}")
        elif st[0] == "Q": L.append(f"Q {st[1]:x}")
        elif st[0] == "APPLY": L += ["G 3", "Q 9", "Q a", "Q b"]
        elif st[0] == "SOUND": L.append(f"G {max(2, min(40, round(st[1] * 48 / 1000)) ):x}")
    return L + (after or [])


def tcl_name(name, nmax):
    return f"wpms_phase6_{name}_{nmax}.tcl"


def tcl_text(name, nmax):
    """The Tcl for quartus_stp: wpms_music.to_tcl over the case's steps, named for Phase 6."""
    return MU.to_tcl(CASES[name](nmax), name=f"phase6_{name}_{nmax}").replace(
        f"wpms_music_phase6_{name}_{nmax}.tcl", tcl_name(name, nmax)).replace(
        "generated by hw/tools/host/wpms_music.py", "generated by hw/tools/host/wpms_phase6_steps.py")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--nmax", type=int, default=0, help="1008 or 2048; 0 = both")
    ap.add_argument("--out", default=HERE)
    a = ap.parse_args()
    for nmax in ([a.nmax] if a.nmax else [1008, 2048]):
        for name in CASES:
            p = os.path.join(a.out, tcl_name(name, nmax))
            open(p, "w").write(tcl_text(name, nmax))
            print(f"wrote {p}")


if __name__ == "__main__":
    main()
