# wpms_phase6_full8_2048.tcl — generated by hw/tools/host/wpms_phase6_steps.py. OUTSIDE WPMS: a stand-in for
# the Layer 4 controller. Run on the PC with the DE10-nano attached and the Phase 6 image loaded:
#   quartus_stp -t wpms_phase6_full8_2048.tcl
source [file join [file dirname [info script]] wpms_issp_host.tcl]
wpms_open
wpms_q 0x009 {GO_SEQ}
wpms_q 0x00B {APPLIED_SAMPLE}
wpms_w 0x200 0x00000100 {full8 0 INBOX[0][0]}
wpms_w 0x201 0x00000000 {full8 0 INBOX[0][1]}
wpms_w 0x202 0xFFD30084 {full8 0 INBOX[0][2]}
wpms_w 0x203 0x001C40F5 {full8 0 INBOX[0][3]}
wpms_w 0x204 0xFFF1D157 {full8 0 INBOX[0][4]}
wpms_w 0x205 0x00000000 {full8 0 INBOX[0][5]}
wpms_w 0x206 0x00000000 {full8 0 INBOX[0][6]}
wpms_w 0x207 0x00000000 {full8 0 INBOX[0][7]}
wpms_w 0x208 0x00000000 {full8 0 INBOX[0][8]}
wpms_w 0x209 0xFFD30084 {full8 0 INBOX[0][9]}
wpms_w 0x20A 0x015A537F {full8 0 INBOX[0][A]}
wpms_w 0x20B 0x000015D8 {full8 0 INBOX[0][B]}
wpms_w 0x20C 0x00000000 {full8 0 INBOX[0][C]}
wpms_w 0x20F 0xFF8E8AB8 {full8 0 INBOX[0][F]}
wpms_w 0x280 0x00000001 {full8 0 RTOUT[0]}
wpms_w 0x288 0x40019FFF {full8 0 COMMIT[0]}
wpms_w 0x210 0x00000100 {full8 1 INBOX[1][0]}
wpms_w 0x211 0x00000000 {full8 1 INBOX[1][1]}
wpms_w 0x212 0xFFD30084 {full8 1 INBOX[1][2]}
wpms_w 0x213 0x001C40F5 {full8 1 INBOX[1][3]}
wpms_w 0x214 0xFFF1D157 {full8 1 INBOX[1][4]}
wpms_w 0x215 0x00000000 {full8 1 INBOX[1][5]}
wpms_w 0x216 0x00000000 {full8 1 INBOX[1][6]}
wpms_w 0x217 0x00000000 {full8 1 INBOX[1][7]}
wpms_w 0x218 0x00000000 {full8 1 INBOX[1][8]}
wpms_w 0x219 0xFFD30084 {full8 1 INBOX[1][9]}
wpms_w 0x21A 0x01861202 {full8 1 INBOX[1][A]}
wpms_w 0x21B 0x000015D8 {full8 1 INBOX[1][B]}
wpms_w 0x21C 0x00000000 {full8 1 INBOX[1][C]}
wpms_w 0x21F 0xFF8E8AB8 {full8 1 INBOX[1][F]}
wpms_w 0x281 0x00000002 {full8 1 RTOUT[1]}
wpms_w 0x289 0x40019FFF {full8 1 COMMIT[1]}
wpms_w 0x220 0x00000100 {full8 2 INBOX[2][0]}
wpms_w 0x221 0x00000000 {full8 2 INBOX[2][1]}
wpms_w 0x222 0xFFD30084 {full8 2 INBOX[2][2]}
wpms_w 0x223 0x001C40F5 {full8 2 INBOX[2][3]}
wpms_w 0x224 0xFFF1D157 {full8 2 INBOX[2][4]}
wpms_w 0x225 0x00000000 {full8 2 INBOX[2][5]}
wpms_w 0x226 0x00000000 {full8 2 INBOX[2][6]}
wpms_w 0x227 0x00000000 {full8 2 INBOX[2][7]}
wpms_w 0x228 0x00000000 {full8 2 INBOX[2][8]}
wpms_w 0x229 0xFFD30084 {full8 2 INBOX[2][9]}
wpms_w 0x22A 0x01B72BEB {full8 2 INBOX[2][A]}
wpms_w 0x22B 0x000015D8 {full8 2 INBOX[2][B]}
wpms_w 0x22C 0x00000000 {full8 2 INBOX[2][C]}
wpms_w 0x22F 0xFF8E8AB8 {full8 2 INBOX[2][F]}
wpms_w 0x282 0x00000003 {full8 2 RTOUT[2]}
wpms_w 0x28A 0x40019FFF {full8 2 COMMIT[2]}
wpms_w 0x230 0x00000100 {full8 3 INBOX[3][0]}
wpms_w 0x231 0x00000000 {full8 3 INBOX[3][1]}
wpms_w 0x232 0xFFD30084 {full8 3 INBOX[3][2]}
wpms_w 0x233 0x001C40F5 {full8 3 INBOX[3][3]}
wpms_w 0x234 0xFFF1D157 {full8 3 INBOX[3][4]}
wpms_w 0x235 0x00000000 {full8 3 INBOX[3][5]}
wpms_w 0x236 0x00000000 {full8 3 INBOX[3][6]}
wpms_w 0x237 0x00000000 {full8 3 INBOX[3][7]}
wpms_w 0x238 0x00000000 {full8 3 INBOX[3][8]}
wpms_w 0x239 0xFFD30084 {full8 3 INBOX[3][9]}
wpms_w 0x23A 0x01EE4929 {full8 3 INBOX[3][A]}
wpms_w 0x23B 0x000015D8 {full8 3 INBOX[3][B]}
wpms_w 0x23C 0x00000000 {full8 3 INBOX[3][C]}
wpms_w 0x23F 0xFF8E8AB8 {full8 3 INBOX[3][F]}
wpms_w 0x283 0x00000001 {full8 3 RTOUT[3]}
wpms_w 0x28B 0x40019FFF {full8 3 COMMIT[3]}
wpms_w 0x240 0x00000100 {full8 4 INBOX[4][0]}
wpms_w 0x241 0x00000000 {full8 4 INBOX[4][1]}
wpms_w 0x242 0xFFD30084 {full8 4 INBOX[4][2]}
wpms_w 0x243 0x001C40F5 {full8 4 INBOX[4][3]}
wpms_w 0x244 0xFFF1D157 {full8 4 INBOX[4][4]}
wpms_w 0x245 0x00000000 {full8 4 INBOX[4][5]}
wpms_w 0x246 0x00000000 {full8 4 INBOX[4][6]}
wpms_w 0x247 0x00000000 {full8 4 INBOX[4][7]}
wpms_w 0x248 0x00000000 {full8 4 INBOX[4][8]}
wpms_w 0x249 0xFFD30084 {full8 4 INBOX[4][9]}
wpms_w 0x24A 0x022C2641 {full8 4 INBOX[4][A]}
wpms_w 0x24B 0x000015D8 {full8 4 INBOX[4][B]}
wpms_w 0x24C 0x00000000 {full8 4 INBOX[4][C]}
wpms_w 0x24F 0xFF8E8AB8 {full8 4 INBOX[4][F]}
wpms_w 0x284 0x00000002 {full8 4 RTOUT[4]}
wpms_w 0x28C 0x40019FFF {full8 4 COMMIT[4]}
wpms_w 0x250 0x00000100 {full8 5 INBOX[5][0]}
wpms_w 0x251 0x00000000 {full8 5 INBOX[5][1]}
wpms_w 0x252 0xFFD30084 {full8 5 INBOX[5][2]}
wpms_w 0x253 0x001C40F5 {full8 5 INBOX[5][3]}
wpms_w 0x254 0xFFF1D157 {full8 5 INBOX[5][4]}
wpms_w 0x255 0x00000000 {full8 5 INBOX[5][5]}
wpms_w 0x256 0x00000000 {full8 5 INBOX[5][6]}
wpms_w 0x257 0x00000000 {full8 5 INBOX[5][7]}
wpms_w 0x258 0x00000000 {full8 5 INBOX[5][8]}
wpms_w 0x259 0xFFD30084 {full8 5 INBOX[5][9]}
wpms_w 0x25A 0x027196C9 {full8 5 INBOX[5][A]}
wpms_w 0x25B 0x000015D8 {full8 5 INBOX[5][B]}
wpms_w 0x25C 0x00000000 {full8 5 INBOX[5][C]}
wpms_w 0x25F 0xFF8E8AB8 {full8 5 INBOX[5][F]}
wpms_w 0x285 0x00000003 {full8 5 RTOUT[5]}
wpms_w 0x28D 0x40019FFF {full8 5 COMMIT[5]}
wpms_w 0x260 0x00000100 {full8 6 INBOX[6][0]}
wpms_w 0x261 0x00000000 {full8 6 INBOX[6][1]}
wpms_w 0x262 0xFFD30084 {full8 6 INBOX[6][2]}
wpms_w 0x263 0x001C40F5 {full8 6 INBOX[6][3]}
wpms_w 0x264 0xFFF1D157 {full8 6 INBOX[6][4]}
wpms_w 0x265 0x00000000 {full8 6 INBOX[6][5]}
wpms_w 0x266 0x00000000 {full8 6 INBOX[6][6]}
wpms_w 0x267 0x00000000 {full8 6 INBOX[6][7]}
wpms_w 0x268 0x00000000 {full8 6 INBOX[6][8]}
wpms_w 0x269 0xFFD30084 {full8 6 INBOX[6][9]}
wpms_w 0x26A 0x02BF8845 {full8 6 INBOX[6][A]}
wpms_w 0x26B 0x000015D8 {full8 6 INBOX[6][B]}
wpms_w 0x26C 0x00000000 {full8 6 INBOX[6][C]}
wpms_w 0x26F 0xFF8E8AB8 {full8 6 INBOX[6][F]}
wpms_w 0x286 0x00000001 {full8 6 RTOUT[6]}
wpms_w 0x28E 0x40019FFF {full8 6 COMMIT[6]}
wpms_w 0x270 0x00000100 {full8 7 INBOX[7][0]}
wpms_w 0x271 0x00000000 {full8 7 INBOX[7][1]}
wpms_w 0x272 0xFFD30084 {full8 7 INBOX[7][2]}
wpms_w 0x273 0x001C40F5 {full8 7 INBOX[7][3]}
wpms_w 0x274 0xFFF1D157 {full8 7 INBOX[7][4]}
wpms_w 0x275 0x00000000 {full8 7 INBOX[7][5]}
wpms_w 0x276 0x00000000 {full8 7 INBOX[7][6]}
wpms_w 0x277 0x00000000 {full8 7 INBOX[7][7]}
wpms_w 0x278 0x00000000 {full8 7 INBOX[7][8]}
wpms_w 0x279 0xFFD30084 {full8 7 INBOX[7][9]}
wpms_w 0x27A 0x0317054D {full8 7 INBOX[7][A]}
wpms_w 0x27B 0x000015D8 {full8 7 INBOX[7][B]}
wpms_w 0x27C 0x00000000 {full8 7 INBOX[7][C]}
wpms_w 0x27F 0xFF8E8AB8 {full8 7 INBOX[7][F]}
wpms_w 0x287 0x00000002 {full8 7 RTOUT[7]}
wpms_w 0x28F 0x40019FFF {full8 7 COMMIT[7]}
wpms_w 0x290 0x0FAC6888 {SWEEP [0 .. 7], P = 8}
wpms_w 0x291 0x40000000 {SWEEP_COMMIT arm}
wpms_w 0x008 0x00000001 {GO: eight blocks and the sweep word}
wpms_wait_applied {full take-set, full load}
after 1000 ;# eight notes, sum of N = NMAX
wpms_q 0x299 {SWEEP_CLOCKS_MAX}
wpms_q 0x018 {STROBE_INTERVAL}
wpms_close
