# wpms_phase6_ew6_2048.tcl — generated by hw/tools/host/wpms_phase6_steps.py. OUTSIDE WPMS: a stand-in for
# the Layer 4 controller. Run on the PC with the DE10-nano attached and the Phase 6 image loaded:
#   quartus_stp -t wpms_phase6_ew6_2048.tcl
source [file join [file dirname [info script]] wpms_issp_host.tcl]
wpms_open
wpms_q 0x009 {GO_SEQ}
wpms_w 0x205 0xFFFFFFFF {INBOX[0][5] LE0 = -1}
wpms_w 0x288 0x40000020 {COMMIT[0] LE0, arm}
wpms_w 0x008 0x00000001 {GO}
wpms_wait_applied {LE0 < 0 in block 0}
after 200 ;# EW6 expected
wpms_close
