# wpms_phase6_first_go_2048.tcl — generated by hw/tools/host/wpms_phase6_steps.py. OUTSIDE WPMS: a stand-in for
# the Layer 4 controller. Run on the PC with the DE10-nano attached and the Phase 6 image loaded:
#   quartus_stp -t wpms_phase6_first_go_2048.tcl
source [file join [file dirname [info script]] wpms_issp_host.tcl]
wpms_open
wpms_q 0x009 {GO_SEQ (the ROM's GO)}
wpms_q 0x00B {APPLIED_SAMPLE (the ROM's GO)}
wpms_w 0x210 0x000000F0 {triad 1 INBOX[1][0]}
wpms_w 0x211 0x00000000 {triad 1 INBOX[1][1]}
wpms_w 0x212 0xFFD30084 {triad 1 INBOX[1][2]}
wpms_w 0x213 0x001A7B20 {triad 1 INBOX[1][3]}
wpms_w 0x214 0xFFF1D157 {triad 1 INBOX[1][4]}
wpms_w 0x215 0x00000000 {triad 1 INBOX[1][5]}
wpms_w 0x216 0x00000000 {triad 1 INBOX[1][6]}
wpms_w 0x217 0x00000000 {triad 1 INBOX[1][7]}
wpms_w 0x218 0x00000000 {triad 1 INBOX[1][8]}
wpms_w 0x219 0xFFD30084 {triad 1 INBOX[1][9]}
wpms_w 0x21A 0x02C036FF {triad 1 INBOX[1][A]}
wpms_w 0x21B 0x000015D8 {triad 1 INBOX[1][B]}
wpms_w 0x21C 0x00000000 {triad 1 INBOX[1][C]}
wpms_w 0x21F 0xFF9C47EC {triad 1 INBOX[1][F]}
wpms_w 0x281 0x00000001 {triad 1 RTOUT[1]}
wpms_w 0x289 0x40019FFF {triad 1 COMMIT[1]}
wpms_w 0x220 0x000000F0 {triad 2 INBOX[2][0]}
wpms_w 0x221 0x00000000 {triad 2 INBOX[2][1]}
wpms_w 0x222 0xFFD30084 {triad 2 INBOX[2][2]}
wpms_w 0x223 0x001A7B20 {triad 2 INBOX[2][3]}
wpms_w 0x224 0xFFF1D157 {triad 2 INBOX[2][4]}
wpms_w 0x225 0x00000000 {triad 2 INBOX[2][5]}
wpms_w 0x226 0x00000000 {triad 2 INBOX[2][6]}
wpms_w 0x227 0x00000000 {triad 2 INBOX[2][7]}
wpms_w 0x228 0x00000000 {triad 2 INBOX[2][8]}
wpms_w 0x229 0xFFD30084 {triad 2 INBOX[2][9]}
wpms_w 0x22A 0x0379E7D7 {triad 2 INBOX[2][A]}
wpms_w 0x22B 0x000015D8 {triad 2 INBOX[2][B]}
wpms_w 0x22C 0x00000000 {triad 2 INBOX[2][C]}
wpms_w 0x22F 0xFF9C47EC {triad 2 INBOX[2][F]}
wpms_w 0x282 0x00000003 {triad 2 RTOUT[2]}
wpms_w 0x28A 0x40019FFF {triad 2 COMMIT[2]}
wpms_w 0x230 0x000000F0 {triad 3 INBOX[3][0]}
wpms_w 0x231 0x00000000 {triad 3 INBOX[3][1]}
wpms_w 0x232 0xFFD30084 {triad 3 INBOX[3][2]}
wpms_w 0x233 0x001A7B20 {triad 3 INBOX[3][3]}
wpms_w 0x234 0xFFF1D157 {triad 3 INBOX[3][4]}
wpms_w 0x235 0x00000000 {triad 3 INBOX[3][5]}
wpms_w 0x236 0x00000000 {triad 3 INBOX[3][6]}
wpms_w 0x237 0x00000000 {triad 3 INBOX[3][7]}
wpms_w 0x238 0x00000000 {triad 3 INBOX[3][8]}
wpms_w 0x239 0xFFD30084 {triad 3 INBOX[3][9]}
wpms_w 0x23A 0x0424362A {triad 3 INBOX[3][A]}
wpms_w 0x23B 0x000015D8 {triad 3 INBOX[3][B]}
wpms_w 0x23C 0x00000000 {triad 3 INBOX[3][C]}
wpms_w 0x23F 0xFF9C47EC {triad 3 INBOX[3][F]}
wpms_w 0x283 0x00000002 {triad 3 RTOUT[3]}
wpms_w 0x28B 0x40019FFF {triad 3 COMMIT[3]}
wpms_w 0x290 0x00000D13 {SWEEP [1, 2, 3]}
wpms_w 0x291 0x40000000 {SWEEP_COMMIT arm}
wpms_w 0x008 0x00000001 {GO}
wpms_wait_applied {C major}
after 1000 ;# C major
wpms_close
