// ============================================================================
//  wpms_decode.vh — GENERATED by hw/tools/gen_decode.py from hw/tools/decode_map.json
//  DO NOT EDIT. Change the JSON and regenerate; pfasm_as.py reads the same JSON.
//  Checked against 03_Sample_Implementations/tools/isa_table_w.json.
//  License: MIT (Layer 3).
// ============================================================================
// Word layout: opcode D0-D3 (Global = 0), mode D4-D7, sub-op D8-D11, register ID D12-D15, immediate D16-D31.
// On the Core's external-operation bus: mode = ext_op_subopcode, {rid, subop} = ext_op_sub_operand,
// imm = ext_op_data.

// ---- operand kinds (how rid and imm are read) ----
localparam [2:0] K_NONE  = 3'd0;   // rid: must be 0; imm: must be 0
localparam [2:0] K_SRC   = 3'd1;   // rid: source ID; imm: signed 16-bit value when rid = IMM (sign-extended to 32 bits); must be 0 otherwise
localparam [2:0] K_DST   = 3'd2;   // rid: destination ID; imm: must be 0
localparam [2:0] K_LIT9  = 3'd3;   // rid: must be 0; imm: unsigned 9-bit ADRS literal in D16-D24; D25-D31 must be 0
localparam [2:0] K_SHIFT = 3'd4;   // rid: must be 0; imm: signed 16-bit shift count: >= 0 arithmetic right, < 0 left (E8 on overflow)

// ---- internal operation codes ----
localparam [3:0] OP_LDA = 4'd0;   // 1.0
localparam [3:0] OP_STA = 4'd1;   // 1.1
localparam [3:0] OP_ADD = 4'd2;   // 1.2
localparam [3:0] OP_SUB = 4'd3;   // 1.3
localparam [3:0] OP_MUL = 4'd4;   // 1.4
localparam [3:0] OP_MAC = 4'd5;   // 1.5
localparam [3:0] OP_SWP = 4'd6;   // 1.6
localparam [3:0] OP_SFT = 4'd7;   // 1.7
localparam [3:0] OP_SAD = 4'd8;   // 2.0
localparam [3:0] OP_LDM = 4'd9;   // 2.1
localparam [3:0] OP_STM = 4'd10;   // 2.2
localparam [3:0] OP_WLV = 4'd11;   // 3.1
localparam [3:0] OP_WJV = 4'd12;   // 3.2
localparam [3:0] OP_WSH = 4'd13;   // 3.3
localparam [3:0] OP_STP = 4'd14;   // 4.0
localparam [3:0] OP_BCP = 4'd15;   // 4.1

// ---- source and destination IDs (master Ch.2 section 2.9; contract) ----
localparam [3:0] SRC_IMM   = 4'd0;
localparam [3:0] SRC_TEMP  = 4'd1;
localparam [3:0] SRC_PPM   = 4'd2;
localparam [3:0] SRC_K     = 4'd3;
localparam [3:0] SRC_I     = 4'd4;
localparam [3:0] SRC_SN    = 4'd5;
localparam [3:0] SRC_SSS   = 4'd6;
localparam [3:0] DST_TEMP  = 4'd0;
localparam [3:0] DST_STORE = 4'd1;

// ---- error codes (error_code[4:0]: bit 4 = profile row EWn) ----
localparam [4:0] ERR_E4  = 5'd4;   // reserved or removed {mode, sub-op}, reserved source/destination ID, or a non-zero must-be-zero field
localparam [4:0] ERR_E5  = 5'd5;   // ADRS outside the map of Map v0.3 section 4 (0x11B-0x1FF) at LDM, STM or an @PPM operand
localparam [4:0] ERR_E8  = 5'd8;   // MUL, MAC or SFT (left) result outside signed 32 bits (SFT as the golden model: SD-13)
localparam [4:0] ERR_EW2 = 5'd18;   // prefetch of a block with N outside [N_MIN, NMAX]
localparam [4:0] ERR_EW3 = 5'd19;   // write into a read-only region (inbox view, COMMIT view, sweep words, status)
localparam [4:0] ERR_EW4 = 5'd20;   // write-window violation: store written outside HK, CUR written outside a packet window, BCP outside HK
localparam [4:0] ERR_EW5 = 5'd21;   // invalid sweep word at BCP (P > 8, repeated block, sum N > NMAX) or sum N of the sweep in effect > NMAX
localparam [4:0] ERR_EW6 = 5'd22;   // STP with Temp < 0

// ---- decoder table: {legal, kind[2:0], op[3:0]} from {mode, sub-op} ----
// Anything not listed (removed rows RTW 2.3, CMT 2.4, PSH 2.5, POP 2.6, WSV 3.0; unassigned sub-ops; modes 5-15) decodes illegal -> E4.
function [7:0] wpms_decode;
    input [3:0] mode;
    input [3:0] subop;
    begin
        case ({mode, subop})
        8'h10: wpms_decode = {1'b1, K_SRC  , OP_LDA};
        8'h11: wpms_decode = {1'b1, K_DST  , OP_STA};
        8'h12: wpms_decode = {1'b1, K_SRC  , OP_ADD};
        8'h13: wpms_decode = {1'b1, K_SRC  , OP_SUB};
        8'h14: wpms_decode = {1'b1, K_SRC  , OP_MUL};
        8'h15: wpms_decode = {1'b1, K_SRC  , OP_MAC};
        8'h16: wpms_decode = {1'b1, K_NONE , OP_SWP};
        8'h17: wpms_decode = {1'b1, K_SHIFT, OP_SFT};
        8'h20: wpms_decode = {1'b1, K_LIT9 , OP_SAD};
        8'h21: wpms_decode = {1'b1, K_NONE , OP_LDM};
        8'h22: wpms_decode = {1'b1, K_NONE , OP_STM};
        8'h31: wpms_decode = {1'b1, K_NONE , OP_WLV};
        8'h32: wpms_decode = {1'b1, K_NONE , OP_WJV};
        8'h33: wpms_decode = {1'b1, K_NONE , OP_WSH};
        8'h40: wpms_decode = {1'b1, K_SRC  , OP_STP};
        8'h41: wpms_decode = {1'b1, K_NONE , OP_BCP};
        default: wpms_decode = 8'h00;
        endcase
    end
endfunction

