// ============================================================================
//  wpms_l1_consts.vh — GENERATED by hw/tools/gen_l1_tables.py. Do not edit.
//  exp2 (Ch.3 §3.5.4): C1, C2 and the table (wpms_exp2_table.hex/.mif) are the
//  customer's oracle's own integers (wpms_layer1_oracle._C1/_C2/_T).
//  Maclaurin core (Ch.2 v1.1): the published realization of hw/tools/l1_model.py
//  — Horner in U = u^2 (u = in-quadrant phase in cycles), c_j = (2 pi)^(2j+1)/(2j+1)!
//  at per-stage power-of-two scales; S1 at 2^23, S2 2^20, S3 2^19, S4 2^19, S5 2^20, c5 2^22.
//  License: MIT (Layer 3).
// ============================================================================
localparam [29:0] EXP2_C1 = 30'd744261118;      // round(ln2 * 2^30)
localparam [27:0] EXP2_C2 = 28'd257941248;      // round(ln2^2/2 * 2^30)
localparam [25:0] SIN_C0  = 26'd52707179;       // 2 pi            * 2^23
localparam [25:0] SIN_C1  = 26'd43349917;       // (2 pi)^3/3!     * 2^20
localparam [25:0] SIN_C2  = 26'd42784653;       // (2 pi)^5/5!     * 2^19
localparam [25:0] SIN_C3  = 26'd40215962;       // (2 pi)^7/7!     * 2^19
localparam [25:0] SIN_C4  = 26'd44101737;       // (2 pi)^9/9!     * 2^20
localparam [25:0] SIN_C5  = 26'd63311520;       // (2 pi)^11/11!   * 2^22
localparam integer SIN_SH5 = 32;   // U*c5 -> S5
localparam integer SIN_SH4 = 31;   // U*S5 -> S4
localparam integer SIN_SH3 = 30;   // U*S4 -> S3
localparam integer SIN_SH2 = 29;   // U*S3 -> S2
localparam integer SIN_SH1 = 27;   // U*S2 -> S1
localparam integer SIN_SH0 = 11;   // u*S1 -> Q0.40
