// ============================================================================
//  wpms_l1_exp2.v — WPMS L1, the exp2 unit (customer Ch.3 §3.5.4)
//  WPMS L1 — exp2 ユニット
// ----------------------------------------------------------------------------
//  License : MIT (Layer 3 sample implementation; illustrative, not normative)
//
//  a = 2^L for one log-amplitude L per clock (Q.30, 54-bit signed), Q1.31 out,
//  6 clocks later. Bit for bit the customer's oracle exp2_q131() (golden):
//      L >= 0          -> 2^31 - 1                    (clamp, a < 1)
//      L < -31 * 2^30  -> 0
//      else  ip = L >> 30 (floor, -31..-1), fr = L - ip*2^30, hi = fr[29:22], lo = fr[21:0]
//            p  = 2^30 + (C1*lo >> 30) + (C2*((lo*lo) >> 30) >> 30)
//            m  = T[hi]*p >> 30                        (< 2^31, ORACLE: max 0x7FFFFFF5)
//            a  = (m << 1) >> (-ip)  =  m >> (-ip - 1)  =  m >> ~ip[4:0]
//  T (256 x 31 bits, one M10K), C1 and C2 are the oracle's own integers
//  (wpms_exp2_table.hex/.mif, wpms_l1_consts.vh, generated by gen_l1_tables.py).
//  The widths are those of the oracle's integers, so no step can round
//  differently: C1*lo 52 bits, lo*lo 44, C2*(lo^2>>30) 42, T*p 61.
//
//  Pipeline: X0 split + clamp flags + table read (registered, M10K)
//            X1 C1*lo, lo*lo       X2 >>30, C2*(lo^2>>30)       X3 p
//            X4 T*p                X5 m >> ~ip, clamps
//  No valid or enable: it computes every clock; LATENCY = 6.
// ----------------------------------------------------------------------------
//  REVISION HISTORY(RH)
//  001 2026-09-29       Claude Code   Add : First version (SILICON_BRIEF_2026-09-27 Phase 4).
// ============================================================================
`timescale 1ns/1ps

module wpms_l1_exp2 #(
    parameter TABLE_HEX = "wpms_exp2_table.hex"
) (
    input  wire               clk,
    input  wire signed [53:0] L,                // Q.30 log2 amplitude (level + shape + MG)
    output reg         [31:0] a                 // Q1.31, 0 .. 2^31-1
);
    localparam integer LATENCY = 6;
`include "wpms_l1_consts.vh"

    // ---- the table (Q2.30, [1, 2)): one M10K, registered read --------------------------
    (* ram_init_file = "wpms_exp2_table.mif" *) reg [30:0] rom [0:255];
    initial $readmemh(TABLE_HEX, rom);

    // ---- X0: split, clamp flags, table read -------------------------------------------------
    reg [30:0] t0;  reg [21:0] lo0;  reg [4:0] sh0;  reg pos0, und0;
    always @(posedge clk) begin
        t0   <= rom[L[29:22]];
        lo0  <= L[21:0];
        sh0  <= ~L[34:30];                                     // -ip - 1 for ip = -31 .. -1
        pos0 <= ~L[53];                                        // L >= 0
        und0 <= (L < -(54'sd31 <<< 30));                       // L < -31 * 2^30
    end

    // ---- X1: C1*lo, lo*lo ---------------------------------------------------------------------
    reg [51:0] c1lo1;  reg [43:0] lolo1;  reg [30:0] t1;  reg [4:0] sh1;  reg pos1, und1;
    always @(posedge clk) begin
        c1lo1 <= EXP2_C1 * lo0;
        lolo1 <= lo0 * lo0;
        t1 <= t0;  sh1 <= sh0;  pos1 <= pos0;  und1 <= und0;
    end

    // ---- X2: >> 30, C2*(lo^2 >> 30) -------------------------------------------------------
    reg [21:0] q1_2;  reg [41:0] c2q2;  reg [30:0] t2;  reg [4:0] sh2;  reg pos2, und2;
    always @(posedge clk) begin
        q1_2 <= c1lo1[51:30];
        c2q2 <= EXP2_C2 * lolo1[43:30];
        t2 <= t1;  sh2 <= sh1;  pos2 <= pos1;  und2 <= und1;
    end

    // ---- X3: p = 2^30 + (C1 lo >> 30) + (C2 (lo^2 >> 30) >> 30) -----------------------------
    reg [30:0] p3;  reg [30:0] t3;  reg [4:0] sh3;  reg pos3, und3;
    always @(posedge clk) begin
        p3 <= 31'h4000_0000 + q1_2 + c2q2[41:30];
        t3 <= t2;  sh3 <= sh2;  pos3 <= pos2;  und3 <= und2;
    end

    // ---- X4: T * p ----------------------------------------------------------------------------------
    reg [61:0] tp4;  reg [4:0] sh4;  reg pos4, und4;
    always @(posedge clk) begin
        tp4 <= t3 * p3;
        sh4 <= sh3;  pos4 <= pos3;  und4 <= und3;
    end

    // ---- X5: m = T p >> 30; a = m >> (-ip - 1); clamps ---------------------------------------
    wire [31:0] m = tp4[61:30];
    always @(posedge clk)
        a <= pos4 ? 32'h7FFF_FFFF : und4 ? 32'd0 : (m >> sh4);
endmodule
